### ISSUE TITLE
[Feature Request and Bug] Compatibility with Particular and Windy barrier blocks

### ISSUE THREAD

**Issue by atLancelot** [wVibzz/ImmersiveWinds#11]
Hello! I have fallen in love with Immersive Winds and had some suggestions I thought would work well with the mod. 

I would love to see some kind of blacklist for particle effects that shouldn't be affected by wind- for example, the water effects from Particular. I've noticed on multiple occasions, the wind will blow the splashes, despite it not making sense to. Super minor addition, but it could help greatly for debugging!
(edit: barrier blocks also are affected by wind)

**Comment by wVibzz** [comment]
This is being worked on currently, I will be adding a config menu that allows you to add a blacklist for particles, hopefully so that it works with every mod. Thanks for the suggestion!

**Comment by atLancelot** [comment]
awesome! :D
this mod is amazing. incredible job! i will be following IW's development closely :)

**Comment by wVibzz** [comment]
added in 0.6
