### ISSUE TITLE
IW only creates config file if modmenu is installed

### ISSUE THREAD

**Issue by Barerock** [wVibzz/ImmersiveWinds#16]
The bullet hole sprites are affected by this mod, it would be nice to have a blacklist to disable certain sprites, preferably with an automatically populated list of every sprite available to the mod in the instance, so each can be ticked individually without having to hunt down file names and stuff, which many people not only can't do, but don't know how to. This could be accomplished in a similar way to how configuration mods populate their config lists, and many mods have such populated lists, but not for things like sprites, which could prove difficult.

**Comment by Barerock** [comment]
https://github.com/MikhailTapio/MrCrayfishGunMod/issues/18 previous issue, Mikhail's version of CGM, which should share parity with the official version, except for the version fix

**Comment by Roadhog360** [comment]
There is already a blacklist to disable any registered particle from being affected by wind. Essentially, exactly what you asked for is already a feature.

**Comment by Barerock** [comment]
> There is already a blacklist to disable any registered particle from being affected by wind. Essentially, exactly what you asked for is already a feature.

Then it doesn't work with connector and forge, unfortunately, which is up to Wvibzz to decide to include within the scope of the mod.

**Comment by Roadhog360** [comment]
I describe my experience with Sinytra Connector... It is definitely compatible.

**Comment by Roadhog360** [comment]
I edited mine through a generated Cloth Config API, try that, perhaps?

**Comment by Barerock** [comment]
> I edited mine through Cloth Config API, try that, perhaps?

I must try this, since I really like it; however, this also means that it's not directly compatible with Forgified Fabric, since it doesn't make a config file, but still modifies the game. I'm no modder, but that seems mildly bad, but not a crisis by any means.

**Comment by Roadhog360** [comment]
This is also not true because I have forgified fabric as well.

**Comment by Barerock** [comment]
> This is also not true because I have forgified fabric as well.

Systems behave differently, and so do versions. What is "true" is completely subjective to device, versions, and cosmic luck.

**Comment by wVibzz** [comment]
What exactly is the issue here?

**Comment by Barerock** [comment]
> What exactly is the issue here?

Other dude seems to have config options and files, I do not. We both are on forge with connector. On my end it's impossible to configure anything at all. I discovered this through moving bullet hole particles and wanting a blacklist, which apparently already exists.

**Comment by wVibzz** [comment]
do you have mod menu installed?

**Comment by Barerock** [comment]
> do you have mod menu installed?

Does modmenu enable the creation/usage of physical files? Cus no, I have configured, which actually works with other forge mods.

**Comment by wVibzz** [comment]
my mod is made for fabric. not forge

however it should just create a config file no matter what. i should be named immersivewind.json

itll look like this

{
  "enableWind": true,
  "particleBlacklist": [
    "happy_villager",
    "azalea_leaf",
    "water_ripple",
    "oak_leaf",
    "damage_indicator",
    "mangrove_leaf",
    "block_marker",
    "spruce_leaf",
    "jungle_leaf",
    "birch_leaf",
    "acacia_leaf",
    "crit",
    "campfire_signal_smoke",
    "water_splash_emitter",
    "campfire_cosy_smoke",
    "water_splash"
  ]
}

**Comment by Barerock** [comment]
That's why I retitled this, and noted that it's your choice to fix it, especially because it may not be within the scope of development.

**Comment by wVibzz** [comment]
got that.

so just making sure. there is no config file within your files?

**Comment by Barerock** [comment]
> got that.
> 
> so just making sure. there is no config file within your files?

None. Checked many times cus thought I was insane. Never found one.

**Comment by Barerock** [comment]
I uninstalled this mod soon after this report, but I'll reinstall again this week to see

**Comment by wVibzz** [comment]
ok got it. 
I ran through my code and noticed that it will only create the config file if there is modmenu installed. but it will still read the file without it.

it seems to be an overlook in my code and i will be fixing this in the next update. Thanks

**Comment by wVibzz** [comment]
also the mod works as normal, you just need the blacklist correct?

**Comment by Barerock** [comment]
> also the mod works as normal, you just need the blacklist correct?

Absolutely, seeing smoke and stuff move around from my chimney's was dope.

**Comment by Barerock** [comment]
I assume Configured will pick it up once it has a config

**Comment by wVibzz** [comment]
Please let me know once the update is out. for now i am going to rename this post. and move it from compatibility to bug

**Comment by wVibzz** [comment]
This is fixed and will be included in the next update. I will leave this issue open for when you can test it.

**Comment by Barerock** [comment]
Unfortunately I can't test this because particular now does an incorrect version check for cloth config and the dev doesn't know that clothconfig is multi-platform and thus it's a particular bug. Not to mention that this version of Connector loaded particular fine for ages, and now particular has changed and it can't. So, I'm sure it works, but particular dev won't listen to me.

**Comment by wVibzz** [comment]
ill keep this closed then. Make a new issue if you find anything!
