### ISSUE TITLE
[Bug] Huge performance deterioration with blacklist

### ISSUE THREAD

**Issue by BakinDP** [wVibzz/ImmersiveWinds#17]
If many particles are rendered, performance worsens, proportionally to a blacklist's size.

https://youtu.be/m9PcN988TR4

Not a big deal on vanilla servers, but in player lobbies with constant particle rain it makes a difference up to a total unplayability.

**Comment by BakinDP** [comment]
You may also notice, that only 1 thread of my CPU is busy, so guess there is a path of improvement!

**Comment by wVibzz** [comment]
the blacklist is buggy already. doesn't always work. so id assume that's why its still affecting the firework particles.

to address the performance issue, that's probably because your spawning thousands of particles. unless you mean something different.

**Comment by BakinDP** [comment]
Any particle causes performance drop, but as I have accidentally found, firework particle is the most or one of the most buggy ones.

It's quite a rare case, but I play on a server that has a lobby, where thousands of these firework particles are spawned at any moment, and once I'm in, the game becomes a powerpoint slideshow and worse. Yet should I join any subserver through this lobby, the performance restores immediately.

Vanilla servers will never spawn that many particles, so this bug propably won't be a problem there.

**Comment by BakinDP** [comment]
If I completely remove the mod, my game handles 16k (a complete maximum of particles on my config) of firework particles with just a 14% FPS drop.

**Comment by wVibzz** [comment]
So i assume that, you just need to blacklist the firework particle and your performance would be fine. And it doesn't work due to the fact that the blacklist itself is buggy.

I am fixing this in the next update. Sorry for any inconvenience.

**Comment by wVibzz** [comment]
OK pretty sure i fixed the issue. The blacklisted particles should line up and work properly.
also for some reason the firework particle is named 'Explosion'. this will be included in the next update
