### ISSUE TITLE
Request: Add serverside support

### ISSUE THREAD

**Issue by jamesgreen26** [wVibzz/ImmersiveWinds#18]
It would be really cool if wind direction and magnitude (oh yeah) was managed by the server, because then you could, for instance, push entities when wind is strong. Also I'm interested in making a compat mod which makes the wind push Valkyrien Skies ships

**Comment by wVibzz** [comment]
serverside support will be coming when I add a localized cloud system and weather system(which is still far out)

I've already played with the idea of very strong winds that push entity's and just couldn't find a way for it to feel right without being mildly annoying at times. I do not plan on adding this feature.
