### ISSUE TITLE
[Feature request] Option to follow clouds direction

### ISSUE THREAD

**Issue by BakinDP** [wVibzz/ImmersiveWinds#4]
If the config will be added, would be nice to have an option for wind following clouds' direction.

**Comment by wVibzz** [comment]
This is an interesting idea!

I do plan on adding a config at some time, but would much rather get my mod to a state the I'm happy with.
Mostly not depending on ParticleRain. There are many updates to come so thanks for the suggestion!

**Comment by wVibzz** [comment]
In the next update 0.6 I will be adding a config, but with my recent plans on adding a weather system I wont be adding the ability for vanilla clouds to follow the direction of the wind. As I will be making my own clouds and such and would rather not spend time on this feature as of current.
