### ISSUE TITLE
Compitability

### ISSUE THREAD

**Issue by DeepVoidLegend** [wVibzz/ImmersiveWinds#6]
compitability with dynamic surroundings

**Comment by wVibzz** [comment]
gonna need more info on what needs to be compatible with this mod/ issues that arise when using both mods

**Comment by DeepVoidLegend** [comment]
particles that should not be shifted by the wind are shifting anyway, for example, circles on the water after rain shift with the wind, and it looks very strange, but most of the particles work as they should, you just need to adjust what should shift with the wind and what should not

**Comment by DeepVoidLegend** [comment]
I am bad at programming, I do not know if it is difficult to do it or not

**Comment by wVibzz** [comment]
i can probably add this in 0.6

**Comment by wVibzz** [comment]
added in 0.6
