### ISSUE TITLE
[Feature?] Quilt Port/Drop Fabric Loader "minor" version (0.15.11 -> 0.15.10)

### ISSUE THREAD

**Issue by tdeverx** [wVibzz/ImmersiveWinds#8]
Not sure if you're using anything in fabric loader 0.15."11", but if its not too much trouble i'd love it if you could drop the minor version to 10 as i'm having a conflict due to the fact i'm stuck with 0.15.10 (at least for now).

A quilt port would be better, but frankly what i suggested above should be much easier if you don't require that version :D

**Comment by wVibzz** [comment]
ill see what i can do and let you know

**Comment by tdeverx** [comment]
Thanks, I really appreciate it!

Also, I just noticed something.. by "Custom wind wisps particles" do you mean a global effect for all biomes? I've been looking for an effect similar to the "Breezy" mod (but minus the hot air balloons lol) but I can't find anything and a lil particle effect isn't worth attempting to move to Forge lmfao

**Comment by wVibzz** [comment]
> Thanks, I really appreciate it!
> 
> Also, I just noticed something.. by "Custom wind wisps particles" do you mean a global effect for all biomes? I've been looking for an effect similar to the "Breezy" mod (minus the hot air balloons lol) but I can't find anything and a lil particle effect isn't worth attempting to move to Forge when you have over 200+ mods lmfao

Sorry that i didn't see your commant,

yes you are right, i intend to add a custom wind particle that shows where the wind is blowing and adds to immersion.
it is going to be somewhat like Breezy, although there wasnt many videos i could find with the wind particle in it.

**Comment by wVibzz** [comment]
I dropped the minor version to .10, hopefully no issues arrive but I guess we will see lol
