### ISSUE TITLE
[Request] - Remove dependency "Particle Rain" (Make it optional)

### ISSUE THREAD

**Issue by MacatMovie** [wVibzz/ImmersiveWinds#9]
Hi. I would like to use the mod only for the wind effects on already existing particles without the weather particles (since it lowers the performance by quite a lot). But I'm not sure if the mod actually needs the "Particle Rain" mod to be able to function properly.

**Comment by wVibzz** [comment]
if you would like, (if you have mod menu installed) you can disable the rendering of their rain, snow and sand particles. and re enable the vanilla rendering system within Particle Rain's config. You can also lower the distance in which the particles spawn if i remember correctly and that can also improve your FPS alot while still getting the full features of my mod!
